[package]
name = "ric-rac-roe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "ric_rac_roe_game"
path = "src/lib.rs"

[[bin]]
name = "ric_rac_roe_runner"
path = "src/bin.rs"